stages:
  - build
  - test
  - package

# python packaging & EOX PyPy releases #
########################################

# build python packages
build_python:
  image: python:3.10-slim-buster
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - pip install --upgrade pip hatch
  script:
    - hatch build

# test python packages
test_wheel:
  image: python:3.10-slim-buster
  needs: ["build_python"]
  stage: test
  script:
    - pip install `ls dist/mapchete_eo*.tar.gz -1 | head -1`[test]
    - mhub --help
    - pytest -v --cov=mapchete_hub_cli tests/

test_tar:
  image: python:3.10-slim-buster
  needs: ["build_python"]
  stage: test
  script:
    - pip install `ls dist/mapchete_eo*.tar.gz -1 | head -1`[test]
    - mhub --help
    - pytest -v --cov=mapchete_hub_cli tests/


# full test suite #

test_mhub:
  image: docker/compose:1.26.0
  needs: ["build_python"]
  stage: test
  timeout: 30m
  retry: 2
  before_script:
    - docker info
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - export MHUB_PORT=$(( 5000 + $RANDOM % 1000 ))
  script:
    # run tests
    - echo "run mhub on port ${MHUB_PORT}"
    - >
      docker-compose \
        -p $CI_JOB_ID \
        -f docker-compose.yml \
        -f docker-compose.test.yml \
        up \
        --exit-code-from mhub_cli_tester \
        --build

  after_script:
    - >
      docker-compose \
        -p $CI_JOB_ID \
        -f docker-compose.yml \
        -f docker-compose.test.yml \
        down \
        -v \
        --rmi all \
        --remove-orphans \
      || true
    - >
      docker-compose \
        -p $CI_JOB_ID \
        -f docker-compose.yml \
        -f docker-compose.test.yml \
        rm -fv \
      || true


# release package

package:
  image: python:3.10-slim-buster
  stage: package
  before_script:
    - pip install --upgrade pip hatch
  script:
    - hatch publish -r https://gitlab.eox.at/api/v4/projects/255/packages/pypi dist/mapchete_hub_cli*
  only:
    - tags
