stages:
  - precommit
  - build
  - test
  - package

# python packaging & EOX PyPy releases #
########################################

precommit:
  stage: codecheck
  tags:
    - privileged
  image: registry.gitlab.eox.at/maps/docker-base/python:3.11-slim-buster
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - pip install pre-commit
  script:
    - pre-commit run --all-files

# build python packages
build_python:
  image: docker.io/python:3.10-slim-buster
  tags:
    - privileged
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - pip install --upgrade pip hatch
  script:
    - hatch build

# test python packages
test_wheel:
  image: docker.io/python:3.10-slim-buster
  tags:
    - privileged  
  needs: ["build_python"]
  stage: test
  before_script:
    - pip install 
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      -r requirements_test.txt
    - pip install
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      --upgrade
      `ls dist/mapchete_hub_cli*.tar.gz -1 | head -1`[test]
  script:
    - mhub --help
    - pytest -v --cov=mapchete_hub_cli tests/ && coverage report

test_tar:
  image: docker.io/python:3.10-slim-buster
  tags:
    - privileged  
  needs: ["build_python"]
  stage: test
  before_script:
    - pip install 
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      -r requirements_test.txt
    - pip install
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      --upgrade
      `ls dist/mapchete_hub_cli*.tar.gz -1 | head -1`[test]
  script:
    - mhub --help
    - pytest -v --cov=mapchete_hub_cli tests/ && coverage report


# INTEGRATION TESTS CURRENTLY NOT WORKING ON OUR CI
# # full test suite #
# test_integration:
#   image: docker/compose:1.26.0
#   needs: ["build_python"]
#   stage: test
#   timeout: 30m
#   retry: 2
#   before_script:
#     - docker info
#     - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
#     - export MHUB_PORT=$(( 5000 + $RANDOM % 1000 ))
#   script:
#     # run tests
#     - echo "run mhub on port ${MHUB_PORT}"
#     - >
#       docker-compose \
#         -p $CI_JOB_ID \
#         -f docker-compose.yml \
#         -f docker-compose.test.yml \
#         up \
#         --exit-code-from mhub_cli_tester \
#         --build
#   after_script:
#     - >
#       docker-compose \
#         -p $CI_JOB_ID \
#         -f docker-compose.yml \
#         -f docker-compose.test.yml \
#         down \
#         -v \
#         --rmi all \
#         --remove-orphans \
#       || true
#     - >
#       docker-compose \
#         -p $CI_JOB_ID \
#         -f docker-compose.yml \
#         -f docker-compose.test.yml \
#         rm -fv \
#       || true


# release package
package:
  image: docker.io/python:3.10-slim-buster
  tags:
    - privileged  
  stage: package
  before_script:
    - pip install --upgrade pip hatch
  script:
    - hatch publish -r https://gitlab.eox.at/api/v4/projects/255/packages/pypi dist/mapchete_hub_cli*
  only:
    - tags
