version: "3.6"

services:

  mhub_tester:
    environment:
      - MHUB_HOST=http://server:${MHUB_PORT:-5000}
    build:
      context: .
      args:
        BASE_IMAGE_NAME: "${BASE_IMAGE_NAME:-mapchete}"
        EOX_PYPI_TOKEN: ${EOX_PYPI_TOKEN}
    command: /bin/bash -c "pytest -v --cov=mapchete_hub_cli && coverage report"
    networks:
      - backend

networks:
  backend:
