version: "3.6"

services:

  mhub_cli_tester:
    build:
      context: .
      args:
        BASE_IMAGE: registry.gitlab.eox.at/maps/mapchete_hub/mhub
        BASE_IMAGE_TAG: "2022.4.0"
        EOX_PYPI_TOKEN: ${EOX_PYPI_TOKEN}
    depends_on:
      - server
    environment:
      - MHUB_HOST=http://server:${MHUB_PORT:-5000}
    command: /bin/bash -c "echo $MHUB_HOST; sleep 5; pytest -v --cov=mapchete_hub_cli && coverage report"
    networks:
      - frontend

networks:
  frontend:
